#!/bin/bash

set -o nounset
set -o errexit

SCRIPTFILE=$(mktemp /tmp/$(basename $0).XXXXXXXX)
if [ $? -ne 0 ] ; then
	echo "$0: failed to create tmp scriptfile" 1>&2
	exit 1
fi

trap "rm -f $SCRIPTFILE" EXIT

if [ $# -ne 3 ] ; then
	echo "usage: $0 <Old Email Address> <New Name> <New Email Address>" 1>&2
	exit 1
fi

oldmail="$1"
newname="$2"
newmail="$3"

#git filter-branch \
# 	-f \
# 	--env-filter \
# 	"GIT_AUTHOR_NAME='$newname'; GIT_AUTHOR_EMAIL='$newmail'; GIT_COMMITTER_NAME='$newname'; GIT_COMMITTER_EMAIL='$newmail';" \
# 	HEAD


cat > $SCRIPTFILE << EOF
	if [ "\$GIT_AUTHOR_EMAIL" = "$oldmail" -o "\$GIT_COMMITTER_EMAIL" = "$oldmail" ] ; then
		GIT_AUTHOR_NAME="$newname"
		GIT_AUTHOR_EMAIL="$newmail"
		GIT_COMMITTER_NAME="$newname"
		GIT_COMMITTER_EMAIL="$newmail"
	fi
EOF

cat $SCRIPTFILE

git filter-branch -f --env-filter "source $SCRIPTFILE" HEAD

# 
# git filter-branch --env-filter '
#       if [ "$GIT_AUTHOR_EMAIL" = "wrong_email@wrong_host.local" -o "$GIT_COMMITTER_EMAIL" = "wrong_email@wrong_host.local" ];
#       then
#               GIT_AUTHOR_NAME="Your Name Here (In Lights)";
#               GIT_AUTHOR_EMAIL="correct_email@correct_host.com";
#               git commit-tree "$@";
#       else
#               git commit-tree "$@";
#       fi' HEAD
